name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: docker/build-push-action@v1
      with: 
        username: ${{ serects.REGISTRY_USERNAME}}
        password: ${{ serects.REGISTRY_PASSWORD}}
        repository: yiren1105/github-action
        tag_with_ref: true
