name: Docker Image CI

on:
  push:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with: 
        username: ${{ secrets.REGISTRY_USERNAME}}
        password: ${{ secrets.REGISTRY_PASSWORD}}
        registry: yiren1105/github-action
        dockerfile: "./Dockerfile"
        tag_with_ref: true
